# Generated by Django 2.0.5 on 2018-08-01 10:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='0.0.0.0', max_length=200, null=True)),
                ('info', models.CharField(blank=True, default='hey', max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('able_to_ping', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('able_to_login', models.TextField(blank=True, default='hey', null=True)),
                ('physical_or_vm', models.CharField(blank=True, default='hey', max_length=200, null=True)),
                ('issues', models.CharField(blank=True, default='hey', max_length=200, null=True)),
            ],
        ),
    ]
