# Generated by Django 2.0.5 on 2018-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hostname',
            field=models.CharField(blank=True, default='hey', max_length=200, null=True),
        ),
    ]
