# Generated by Django 2.0.5 on 2018-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180801_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='able_to_login',
            field=models.CharField(blank=True, default='hey', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='able_to_ping',
            field=models.CharField(blank=True, default='hey', max_length=200, null=True),
        ),
    ]
